name: 9
timestamp: 1448927385
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1448927385
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
